name: PKCS11 Tests

on: [push, pull_request]

jobs:
  build:
    name: Building JSS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - 34
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build runner image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            OS_VERSION=${{ matrix.os }}
            BUILD_OPTS=--with-timestamp --with-commit-id
          tags: jss-runner
          target: jss-runner
          outputs: type=docker,dest=pkcs11-runner.tar

      - name: Store runner image
        uses: actions/cache@v3
        with:
          key: pkcs11-runner-fedora:${{ matrix.os }}-${{ github.run_id }}
          path: pkcs11-runner.tar

  pkcs11-constants-test:
    name: Testing PKCS11 Constants
    needs: build
    runs-on: ubuntu-latest
    env:
      SHARED: /tmp/workdir/jss
    strategy:
      matrix:
        os:
          - 34
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Retrieve runner image
        uses: actions/cache@v3
        with:
          key: pkcs11-runner-fedora:${{ matrix.os }}-${{ github.run_id }}
          path: pkcs11-runner.tar

      - name: Load runner image
        run: docker load --input pkcs11-runner.tar

      - name: Run container
        run: |
          IMAGE=jss-runner \
          NAME=jss \
          HOSTNAME=jss.example.com \
          tests/bin/runner-init.sh

      - name: Install dependencies
        run: docker exec jss dnf install -y nss-util-devel python3 java-devel

      - name: Generate PKCS11 constants
        run: |
          docker exec jss python3 $SHARED/tools/build_pkcs11_constants.py \
                   --pkcs11t /usr/include/nss3/pkcs11t.h \
                   --pkcs11n /usr/include/nss3/pkcs11n.h \
                   -o PKCS11Constants.java \
                   --verbose
          docker exec jss diff PKCS11Constants.java $SHARED/src/main/java/org/mozilla/jss/pkcs11/PKCS11Constants.java
